SELECT TOP(500) * FROM RSP..Retail_sales;
go
SELECT DISTINCT STORE_ID FROM RSP..Retail_sales;
SELECT DISTINCT PRODUCT_ID FROM RSP..Retail_sales;
SELECT DISTINCT STORE_LOCATION FROM RSP..Retail_sales;
SELECT DISTINCT PRODUCT_CATEGORY FROM RSP..Retail_sales;
GO
SELECT PRODUCT_CATEGORY, SUM(UNITS_SOLD) AS Total_Units_Sold, SUM(SALES_REVENUE_USD) AS Total_Sales_Revenue 
FROM RSP..RETAIL_SALES GROUP BY PRODUCT_CATEGORY ORDER BY Total_Units_Sold DESC;
SELECT PRODUCT_ID, SUM(UNITS_SOLD) AS TOTAL_UNITS_SOLD, SUM(SALES_REVENUE_USD) AS TOTAL_SALES_REVENUE 
FROM RSP..RETAIL_SALES GROUP BY PRODUCT_ID ORDER BY TOTAL_SALES_REVENUE DESC;
SELECT PRODUCT_CATEGORY, COUNT(PRODUCT_ID) AS COUNT_PI FROM RSP..RETAIL_SALES GROUP BY PRODUCT_CATEGORY ORDER BY COUNT_PI DESC;
GO

SELECT RS.STORE_LOCATION, US, RS.RN AS UNITS_SOLD_RANK, RSU, TAB1.RN AS SALES_REVENUE_RANK FROM 
(SELECT STORE_LOCATION, SUM(UNITS_SOLD) AS US, ROW_NUMBER() OVER (ORDER BY SUM(UNITS_SOLD) DESC) AS RN FROM RSP..RETAIL_SALES 
GROUP BY STORE_LOCATION ) AS RS 
JOIN
(SELECT STORE_LOCATION, SUM(SALES_REVENUE_USD) AS RSU, ROW_NUMBER() OVER (ORDER BY SUM(SALES_REVENUE_USD) DESC) AS RN
FROM RSP..RETAIL_SALES GROUP BY STORE_LOCATION ) AS TAB1 ON RS.STORE_LOCATION = TAB1.STORE_LOCATION ORDER BY RS.US DESC ;
GO

SELECT STORE_LOCATION, PRODUCT_CATEGORY, SUM(UNITS_SOLD) AS US , SUM(SALES_REVENUE_USD) AS SRU 
FROM RSP..RETAIL_SALES GROUP BY STORE_LOCATION, PRODUCT_CATEGORY ORDER BY STORE_LOCATION, SRU DESC;
GO
SELECT RSU AS TOTAL_SALES_REVENUE, RN1,T1.STORE_LOCATION, US AS TOTAL_UNITS_SOLD, RN, 
TOTAL_DISC_PERCENTAGE, RN2, TOTAL_MARKETING_SPEND, RN3
FROM (SELECT STORE_LOCATION, SUM(SALES_REVENUE_USD) AS RSU, ROW_NUMBER() OVER (ORDER BY SUM(SALES_REVENUE_USD) DESC) AS RN1,
SUM(DISCOUNT_PERCENTAGE) AS TOTAL_DISC_PERCENTAGE, ROW_NUMBER() OVER (ORDER BY SUM(DISCOUNT_PERCENTAGE) DESC) AS RN2,
SUM(MARKETING_SPEND_USD) AS TOTAL_MARKETING_SPEND, ROW_NUMBER() OVER (ORDER BY SUM(MARKETING_SPEND_USD) DESC) AS RN3
FROM RSP..RETAIL_SALES GROUP BY STORE_LOCATION ) AS T1
INNER JOIN 
(SELECT STORE_LOCATION, SUM(UNITS_SOLD) AS US, ROW_NUMBER() OVER (ORDER BY SUM(UNITS_SOLD) DESC) AS RN FROM RSP..RETAIL_SALES GROUP BY STORE_LOCATION ) AS T2
ON T1.STORE_LOCATION = T2.STORE_LOCATION ORDER BY RN1;
go
SELECT AVG(UNITS_SOLD) AS US, AVG(SALES_REVENUE_USD) AS SRU, HOLIDAY_EFFECT FROM RSP..RETAIL_SALES GROUP BY Holiday_Effect ORDER BY SRU DESC;
SELECT AVG(UNITS_SOLD) AS US, AVG(SALES_REVENUE_USD) AS SRU, DAY_OF_THE_WEEK FROM RSP..RETAIL_SALES GROUP BY DAY_OF_THE_WEEK ORDER BY SRU DESC;
SELECT AVG(UNITS_SOLD) AS US, AVG(SALES_REVENUE_USD) AS SRU, YEAR FROM RSP..RETAIL_SALES GROUP BY YEAR ORDER BY SRU DESC;
SELECT AVG(UNITS_SOLD) AS US, AVG(SALES_REVENUE_USD) AS SRU, MONTH FROM RSP..RETAIL_SALES GROUP BY MONTH ORDER BY SRU DESC;

SELECT
    AVG(UNITS_SOLD) AS US,
	AVG(SALES_REVENUE_USD) AS SRU,
    CASE
        WHEN MONTH IN (1, 2, 3) THEN 'Q1'
        WHEN MONTH IN (4, 5, 6) THEN 'Q2'
        WHEN MONTH IN (7, 8, 9) THEN 'Q3'
        WHEN MONTH IN (10, 11, 12) THEN 'Q4'
        ELSE 'Unknown' -- Handle potential unexpected month values
    END AS Quarter
FROM
    RSP..RETAIL_SALES
GROUP BY
    CASE
        WHEN MONTH IN (1, 2, 3) THEN 'Q1'
        WHEN MONTH IN (4, 5, 6) THEN 'Q2'
        WHEN MONTH IN (7, 8, 9) THEN 'Q3'
        WHEN MONTH IN (10, 11, 12) THEN 'Q4'
        ELSE 'Unknown'
    END
ORDER BY
    SRU DESC; 